defaults: &defaults
  docker:
    - image: circleci/node:6.14
  working_directory: ~/styleguide


version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - persist_to_workspace:
          root: ~/styleguide
          paths:
            - node_modules
            - dist

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/styleguide
      - run:
          name: deploy
          command: |
            git config --global user.email "circleci@itsinthenode.com"
            git config --global user.name "CircleCI Bot"
            npm run deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
