defaults: &defaults
  docker:
    - image: circleci/node:6.14
  working_directory: ~/styleguide

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - dependency-cache-{{ .Branch }}-
            - dependency-cache-master
            - dependency-cache-
      - run:
          name: install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn run test
      - persist_to_workspace:
          root: ~/styleguide
          paths:
            - node_modules
            - dist

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/styleguide
      - run:
          name: fix deployment (better use different deployment library)
          command: |
            cd node_modules/gulp-gh-pages/
            npm install --save gift@0.10.2
      - run:
          name: deploy
          command: |
            git config --global user.email "circleci@itsinthenode.com"
            git config --global user.name "CircleCI Bot"
            yarn run deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
